# Site settings
title: Kaitlin Thaney + David Riordan Wedding | May 21, 2016 | Brooklyn, New York
# email: tktk
description:  Wedding of Kaitlin Thaney to David Riordan. This is what happens when you let a bunch of nerds run wild together. May 21, 2016 | Brooklyn, New York
timezone: America/New_York
url: "http://thaneyriordan.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
